call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'w0rp/ale'
Plug 'kevindurb/vim-splits'
Plug 'kevindurb/vim-quicksilver'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-fugitive'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-vinegar'
Plug 'moll/vim-node'
Plug 'junegunn/seoul256.vim'
Plug 'kshenoy/vim-signature'
Plug 'joonty/vdebug'
Plug 'itchyny/lightline.vim'
call plug#end()
let g:ctrlp_root_markers = [
\ 'package.json',
\ '.eslintrc.js',
\ '.tern-project',
\ '.git',
\]
let g:ale_linters = {
\ 'javascript': ['eslint'],
\ 'javascript jsx': ['eslint'],
\}
let g:lightline = {
\ 'colorscheme': 'seoul256',
\}
let g:seoul256_background = 239
set clipboard=unnamed
set number
set background=dark
set cursorline
set hlsearch
set ignorecase
set smartcase
set relativenumber
set nowrap
set colorcolumn=100
set backupcopy=yes
colo seoul256
let mapleader=','
nnoremap <leader>r :so $HOME/.vim/vimrc<CR>
nnoremap <leader>n :noh<CR>
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
map <Leader>dc :call ToggleVDebugOption('continuous_mode')<CR>
map <Leader>db :call ToggleVDebugOption('break_on_open')<CR>
set tags=.tags;/ " Start in :pwd and search up for a tags file
set wildignore=
set wildignore+=*/node_modules/*
set wildignore+=*/vendor/*
set wildignore+=*.min.js
let g:vdebug_options = {}
let g:vdebug_options['path_maps'] = {
  \ '/var/www/app': '/Users/aglassford/Development/churchcommunitybuilder/app'
  \ }
let g:vdebug_options['server'] = ''
let g:vdebug_options['break_on_open'] = 0
let g:vdebug_options['continuous_mode'] = 0
let g:vdebug_features = {}
let g:vdebug_features['max_children'] = 1024
function! ToggleVDebugOption(opt)
  if g:vdebug_options[a:opt] == 0
    let g:vdebug_options[a:opt] = 1
    echo 'VDebug ' . a:opt . ': On'
  else
    let g:vdebug_options[a:opt] = 0
    echo 'VDebug ' . a:opt . ': Off'
  endif
endfunction



